#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find ~/gits -mindepth 1 -maxdepth 2 -type d | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

#if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
#	tmux new-session -d -s $selected_name
#	tmux send-keys -t $selected_name "vim $selected" Enter
#	tmux attach -t $selected_name
#	exit 0
#fi

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -d -s $selected_name
	tmux send-keys -t $selected_name "vim $selected" Enter
	tmux attach -t $selected_name
	exit 0
fi

#i ! tmux has-session -t=$selected_name 2> /dev/null; then
#	echo not has session
#	tmux new-session -d -s $selected_name
#	tmux send-keys -t $selected_name "vim $selected" Enter
#	tmux attach -t $selected_name
#	exit 0
#fi

#tmux switch-client -t $selected_name
if [[ -z $TMUX ]]; then
	tmux attach-session -t $selected_name
else
	tmux switch-client -t $selected_name
fi
