
# CapsLock acts as Escape
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

#xsetbg /home/charles/sunset.jpg
feh --bg-scale ~/.local/wallpapers/sunset.jpg

sxhkd -c $HOME/.config/sxhkd/sxhkdrc

# Start dwm
exec dwm

